    var criteria_format_rules = {
        vpnservice: {importance:"more"},
        basedincountry: {importance:"less"},
        fourteeneyescountry: {importance:"more", danger:"Five,Not Disclosed", warning:"Nine,Fourteen,Cooperative,Owned", safe:"No"},
        enemyoftheinternet: {importance:"more", danger:"Yes,Not Disclosed", warning:"Owned", safe:"No"},
        traffic: {importance:"more", danger:"Yes,?", safe:"No"},
        dnsrequests: {danger:"Yes,?", safe:"No"},
        timestamps: {danger:"Yes,?", safe:"No"},
        bandwidth: {danger:"Yes,?", safe:"No"},
        ipaddress: {importance:"more", danger:"Yes,?", safe:"No"},
        anonymouspaymentmethod: {danger:"No", warning:"Email", safe:"Yes"},
        acceptsbitcoin: {danger:"No", safe:"Yes"},
        pgpkeyavailable: {danger:"No", safe:"Yes"},
        meetsprivacytoolsiocriteria: {danger:"No", safe:"Yes", importance:"more"},
        dnsservers: {danger:"No", safe:"Yes", importance:"more"},
        ipv6supportedblocked: {danger:"No", safe:"Yes"},
        offersopenvpn: {importance:"more", danger:"No", safe:"Yes"},
        supportsmultihop: {safe:"Yes"},
        supportstcpport443: {safe:"Yes"},
        supportsobfsproxy: {safe:"Yes"},
        supportssocks: {safe:"Yes"},
        supportsssltunnel: {safe:"Yes"},
        supportssshtunnel: {safe:"Yes"},
        otherproprietaryprotocols: {warning:"Yes"},
        blockssmtpauthent: {importance:"more", danger:"Yes", warning:"Some", safe:"No"},
        blocksp2p: {importance:"more", danger:"Yes", warning:"Some", safe:"No"},
        dedicatedorvirtual: {danger:"Virtual", safe:"Dedicated"},
        defaultprovided: {warning:"Blowfish-128,Blowfish-256", safe:"AES-128,AES-256"},
        strongestdataencryption: {danger:"MPPE-128", warning:"Blowfish-128,Blowfish-256", safe:"AES-128,AES-256"},
        weakesthandshakeencryption: {danger:"MS-CHAPv2,RSA-RC4,RSA-1024", safe:"DH-2048,RSA-2048,RSA-4096"},
        strongestprovided: {danger:"MS-CHAPv2,RSA-RC4,RSA-1024", safe:"DH-2048,RSA-2048,RSA-4096"},
        numofconnections: {danger:"0,1,2", warning:"3,4", safe:"5+"},
        numfcountries: {danger:"0,1,2", warning:"3,4,5,6,7,8,9", safe:"10+"},
        numofservers: {danger:"0", warning:"1,2,3,4,5,6,7,8,9", safe:"10+"},
        linuxsupportmanual: {danger:"No", warning:"Partial", safe:"Yes"}
    }
    
    var criteria_popup_text = {
        VPNSERVICE: "Name of the VPN service provider.",
        VPNReviewBadges: "To emphasize one or more aspects of the VPN in question. These badges may have tongue-in-cheek names meant to entertain, but are strictly the opinion of ThatOnePrivacySite.net",
        JURISDICTIONBasedInCountry: "Negative scores are not necessarily reflective of the companies or their polciies, only the countries they’re based in.",
        JURISDICTIONFourteenEyes: "'Owned' means a country/location isn’t a Five-eyes country itself, but is a territory or commonwealth of one. Second tier 'Cooperative' countries are determined by Privacy International",
        JURISDICTIONEnemyoftheInternet: "Based on Reporters without Borders’, 2014 “Enemies of the Internet” Report.",
        LOGGINGLogsTraffic: "These metrics are collected from the official websites and other reuptable sources.  This section takes each company at their word.  It’s up to the user to decide who is trustworthy. The term “logging” is referring to LONG TERM storage of this information, and not REAL TIME “monitoring”. Again – just because a company may not log, this does NOT mean that you can’t be monitored in real time by the service.",
        LOGGINGLogsDNSRequests: "These metrics are collected from the official websites and other reuptable sources.  This section takes each company at their word.  It’s up to the user to decide who is trustworthy. The term “logging” is referring to LONG TERM storage of this information, and not REAL TIME “monitoring”. Again – just because a company may not log, this does NOT mean that you can’t be monitored in real time by the service.",
        LOGGINGLogsTimestamps: "These metrics are collected from the official websites and other reuptable sources.  This section takes each company at their word.  It’s up to the user to decide who is trustworthy. The term “logging” is referring to LONG TERM storage of this information, and not REAL TIME “monitoring”. Again – just because a company may not log, this does NOT mean that you can’t be monitored in real time by the service.",
        LOGGINGLogsBandwidth: "Some services limit the bandwidth of the user. When a company’s privacy policy explicitly states no bandwidth usage logging, you can be more sure they’re serious and don’t have an invisible, unadvertised cap.",
        LOGGINGLogsIPAddress: "These metrics are collected from the official websites and other reuptable sources.  This section takes each company at their word.  It’s up to the user to decide who is trustworthy. The term “logging” is referring to LONG TERM storage of this information, and not REAL TIME “monitoring”. Again – just because a company may not log, this does NOT mean that you can’t be monitored in real time by the service.",
        ACTIVISMAnonymousPaymentMethod: "Service offers at least one payment method that does not require personal information. “Email” in this field is considered better than a No, since it may or may not be tethered to an individuals identity. This does NOT count companies that claim that you can just falsify personal info and technically be anonymous.  It’s to highlight companies that don’t ask for it in the first place.",
        ACTIVISMAcceptsBitcoin: "",
        ACTIVISMPGPKeyAvailable: "",
        ACTIVISMMeetsPrivacyToolsIOCriteria: "<ul> <li>Does not log traffic.</li> <li>Operating outside the USA or other Five Eyes countries.</li> <li>Has OpenVPN software support.</li> <li>Accepts Bitcoin, cash, debit cards or cash cards as a payment method.</li> <li>No personal information is required to create an account. Only username, password and Email.</li> </ul> More info at privacytools.io",
        LEAKPROTECTION1stPartyDNSServers: "",
        LEAKPROTECTIONIPv6SupportedBlocked: "",
        PROTOCOLSOffersOpenVPN: "",
        OBFUSCATIONSupportsMultihop: "Sometimes it’s useful to obfuscate the fact that your traffic is generated by a VPN. For example, if your ISP or Network Administrator is blocking certain VPN protocls for some reason. These fields represent different methods of obfuscating VPN traffic so that it’s not as easily detected and blocked.",
        OBFUSCATIONSupportsTCPPort443: "Sometimes it’s useful to obfuscate the fact that your traffic is generated by a VPN. For example, if your ISP or Network Administrator is blocking certain VPN protocls for some reason. These fields represent different methods of obfuscating VPN traffic so that it’s not as easily detected and blocked.",
        OBFUSCATIONSupportsObfsproxy: "Sometimes it’s useful to obfuscate the fact that your traffic is generated by a VPN. For example, if your ISP or Network Administrator is blocking certain VPN protocls for some reason. These fields represent different methods of obfuscating VPN traffic so that it’s not as easily detected and blocked.",
        OBFUSCATIONSupportsSOCKS: "Sometimes it’s useful to obfuscate the fact that your traffic is generated by a VPN. For example, if your ISP or Network Administrator is blocking certain VPN protocls for some reason. These fields represent different methods of obfuscating VPN traffic so that it’s not as easily detected and blocked.",
        OBFUSCATIONSupportsSSLTunnel: "Sometimes it’s useful to obfuscate the fact that your traffic is generated by a VPN. For example, if your ISP or Network Administrator is blocking certain VPN protocls for some reason. These fields represent different methods of obfuscating VPN traffic so that it’s not as easily detected and blocked.",
        OBFUSCATIONSupportsSSHTunnel: "Sometimes it’s useful to obfuscate the fact that your traffic is generated by a VPN. For example, if your ISP or Network Administrator is blocking certain VPN protocls for some reason. These fields represent different methods of obfuscating VPN traffic so that it’s not as easily detected and blocked.",
        OBFUSCATIONOtherProprietaryProtocols: "",
        PORTBLOCKINGAuthSMTP: "A “Some” in this field means that the companies’ support team may be willing to whitelist your E-Mail providers SMTP server upon request.  Another possibility is the company supports some workaround method.",
        PORTBLOCKINGP2P: "Services marked as blocking “Some” P2P, usually only blocks it on servers dedicated for streaming.  Other possibilities are that P2P user is throttled – or worse banned.  The user is responsible for researching further based on their needs.",
        SPEEDSUSServerAverage: "Speed Tests are run in the course of performing reviews (methodology and test setup can be found here).  Averages are used for this figure.  International speeds are averaged from all international tests run in a given review.  A “0.00” in this field does NOT mean no speed, just that there isn’t data to populate the field.",
        SPEEDSIntlServerAverage: "Speed Tests are run in the course of performing reviews (methodology and test setup can be found here).  Averages are used for this figure.  International speeds are averaged from all international tests run in a given review.  A “0.00” in this field does NOT mean no speed, just that there isn’t data to populate the field.",
        SERVERSDedicatedorVirtual: "",
        SECURITYDefaultDataEncryption: "",
        SECURITYStrongestDataEncryption: "",
        SECURITYWeakestHandshakeEncryption: "",
        SECURITYStrongestHandshakeEncryption: "",
        AVAILABILITYofConnections: "A 25 in this field actually indicates no advertised limit for simultaneous connections.  (Done this way for conditional formatting purposes only)",
        AVAILABILITYofCountries: "Note that some companies report physical server locations, and some use tricks to make a server endpoint appear to be in another country when it really isn’t. Note, that in many cases where the number of countries is unusually high, THIS IS THE CASE. Do your own research on a case by case basis if this is an important metric for you.",
        AVAILABILITYofServers: "Note that some companies report physical server count, and some report virtual server count (to inflate the numbers). Do your own research on a case by case basis if this is an important metric for you.",
        SUPPORTLinuxManualConfig: "This field is a “yes” if .ovpn files are available and ready to use in Linux Network Manager, not CLI.  If some tweaking is needed, or if the support team of a given service has to specially make and email these, this field will be “partial”.  If no files are readily available, this field will be “no”.",
        WEBSITEofPersistentCookies: "Using webcookies.org – persistent cookies",
        WEBSITEofExternalTrackers: "Using webcookies.org – third party cookies",
        WEBSITEofProprietaryAPIs: "This field is derived from a urlquery scan of each service’s website. Not all services are of equal concern (or even concern at all).  This is a loose indication of how committed to free software a company is.",
        WEBSITEServerSSLRating: "Run using Qualys SSL Labs – SSL Server Test Tool",
        WEBSITESSLCertissuedto: "",
        PRICINGMonthAnnualPricing: "Pricing is based off of normal rates, and doesn’t take into consideration promotions, coupons, or sales.",
        PRICINGConnectionMonth: "",
        PRICINGFreeTrial: "",
        PRICINGRefundPeriodDays: "Often, payments made by cash or bitcoin CANNOT be refunded. User should research as needed.",
        ETHICSContradictoryLoggingPolicies: "This field indicates a company who advertises a zero logs or absolutely no logs policy in their marketing, but upon further inspection do keep logs to some extent. This does NOT mean that the company in question has provided details about their logging policy in their terms or privacy policies, only that they have not claimed “no logging”, then immediately disproved it.",
        ETHICSFalselyClaims100Effective: "No security or privacy setup truly offers 100% protection or is a bulletproof solution. When a company uses hyperbole or otherwise claims 100% effectiveness for anonymity, privacy, security, or generally gives this impression – it misleads potential customers that don’t know better and can harm the user who expects it to be true. Some claims are more blatant than others, but any claim that could be construed as a surefire way to be anonymous is counted.",
        ETHICSIncentivizesSocialMediaSpam: "These companies offer rewards such as extra data allowances or free service time to users posting about their service on social media. This clogs up research channels and pads the number of likes (and therefore attention) a given service or feature has that it might not otherwise. This also includes affiliates who post “deals” on behalf of the company to bring in traffic. This in turn could mislead the honest customer.",
        POLICIESForbidsSpam: "Email or comment spam",
        POLICIESRequiresEthicalCopy: "Companies that expect their affiliates to use ethically acceptable copy (keywords, terms, metatags, descriptions and webdesigns) in their advertising campaigns. Ethically acceptable copy is considered copy that is in no way deceptive, nor imposes upon the trademarks, copyrights or intellectual property of another product, company or entity. Purchasing advertisements on search engines with the names of the represented companies is strictly prohibited.",
        POLICIESRequiresFullDisclosure: "This includes, but is not limited to, Federal Trade Commission 16 CFR Part 255 (or equivalent): Guides Concerning the Use of Endorsements and Testimonials in Advertising, which requires, among other criteria, that material connections between advertisers and endorsers be disclosed. This means that directories, review/rating sites, blogs and other websites, email or collateral that purport to provide an endorsement or assessment of an advertiser must prominently disclose the fact financial or inkind compensation is provided from the advertiser.",
        AFFILIATESPracticeEthicalCopy: "Affiliates are free agents bound to the terms of the companies they represent and given commissions or incentives to funnel traffic and referrals to the company’s site via affiliate links. While companies are not directly responsible for their affiliates actions, they have a responsibility to keep affiliates and resellers operating within the terms of their partnership. Ideally this means not spamming, breaking copyright, and providing full disclosure.",
        AFFILIATESGiveFullDisclosure: "Affiliates are free agents bound to the terms of the companies they represent and given commissions or incentives to funnel traffic and referrals to the company’s site via affiliate links. While companies are not directly responsible for their affiliates actions, they have a responsibility to keep affiliates and resellers operating within the terms of their partnership. Ideally this means not spamming, breaking copyright, and providing full disclosure.",
        GOODPrivacy: "Privacy – Doesn’t ask for more personal info than an email address (without verifying), offers at least one anonymous payment method, clear no logs policy.",
        GOODFeatures: "Features – PGP Key available, offers two or more obfuscation methods, officially supports a manual .ovpn config setup without the need to contact support.  Supports OpenVPN.",
        GoodTech: "Technical – Solid service configuration: Uses 1st party DNS servers, Doesn’t block ports (at least some servers are kept open), US speeds are 80%+ and International speeds are 15%+.  Uses dedicated servers, default encryption is strong.",
        GOODElegance: "Elegance – Terms and policies are relatively simple, provides an easy method to test service (whether official trial or refund period), allows for refund without bandwidth or session limits.",
        GOODSupport: "Support – Support is both speedy (initial response less than 24 hours) and helpful (able to resolve at least basic issues within 24 hours of first response).",
        GOODWebsite: "Website – Design of the site is easy to follow and find things on, less than 3 cookies and less than 3 trackers, less than 3 proprietary APIs, “A” or higher SSL rating, Self issued SSL cert.",
        GOODEthics: "Ethics – Less than 2 ethics “violations”, if service has an affiliate program, terms must require ethical behavior, appears to actively support good causes and promote good business practices.",
        GOODChoice: "That One Privacy Guy’s Choice – This represents an outstanding review, including no major faults.  The ultimate badge to be achieved.",
        BADExposed: "Exposed – Requires personal info, logs everything or almost everything, offers no anonymous payment method.",
        BADBasic: "Basic – No manual configuration setup support whatsoever.  Linux and Android (manual) are afterthoughts if thoughts at all.  Generally unfriendly to advanced users who prefer setting things up themselves.",
        BADBroken: "Broken – Weak encryption used by default, default settings are lacking in an egregious way.  Ports blocked, etc.",
        BADObtuse: "Obtuse – Terms are out of control and too long.  Company goes out of their way to absolve themselves of all responsibility and nail down the customer.",
        BADSilent: "Silent – Support took 3 days or more to even respond to an initial request for assistance (if they replied at all).  Given even if they do respond but still have nothing useful to say.",
        BADWebsiteBad: "Website – Website relies too heavily on cookies and trackers (more than 10), proprietary APIs (more than 10), has a C or lower SSL rating, uses Cloudflare/Incapsula or has no SSL cert at all.",
        BADShady: "Shady – Has more than 4 ethics “violations” on the comparison chart.  Company engages in affiliate marketing without limits.",
        BADPileofJunk: "Pile of Junk – Avoid at all costs.  Too many things wrong to count.  The ultimate demerit one can “earn”."
    }
    
